apiVersion: v1
kind: Service
metadata:
  name: sonar-svc
spec:
  type: NodePort
  selector:
    release: sonarqube
    statefulset.kubernetes.io/pod-name: sonarqube-sonarqube-0
    app: sonarqube
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30080